namespace: decisionrules

domain:
  client: "yourdomain.local"
  api: "api.yourdomain.local"
  bi: "bi.yourdomain.local"

env:
  client:
    API_URL: "https://api.yourdomain.local"
    BI_API_URL: "https://bi.yourdomain.local"
  server:
    REDIS_URL: "redis://host.docker.internal:6379"
    MONGO_DB_URI: "mongodb://host.docker.internal:27017"
    CLIENT_URL: "https://yourdomain.local/#"
    API_URL: "https://api.yourdomain.local"
    LICENSE_KEY: ""
  bi:
    BI_MONGO_DB_URI: "mongodb://host.docker.internal:27017"

images:
  client: decisionrules/client
  server: decisionrules/server
  bi: decisionrules/business-intelligence

resources:
  client:
    requests:
      cpu: 250m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 256Mi
  server:
    requests:
      cpu: 1000m
      memory: 1Gi
    limits:
      cpu: 2000m
      memory: 2Gi
  bi:
    requests:
      cpu: 1000m
      memory: 1Gi
    limits:
      cpu: 2000m
      memory: 4Gi

replicaCount:
  client: 2
  server: 2
  bi: 2

autoscalingServer:
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 60