apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: decisionrules-ingress
  namespace: {{ .Values.namespace }}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: "/"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - {{ .Values.domain.client }}
    - {{ .Values.domain.api }}
    - {{ .Values.domain.bi }}
    secretName: echo-tls
  rules:
  - host: {{ .Values.domain.client }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: decisionrules-client-service
            port:
              number: 80
  - host: {{ .Values.domain.api }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: decisionrules-server-service
            port:
              number: 8080
  - host: {{ .Values.domain.bi }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: decisionrules-bi-service
            port:
              number: 8082